### Create an account
POST {{api_endpoint}}/accounts

{
  "userId": "{{userId}}",
  "name": "{{name}}",
  "image": "{{image}}",
  "password": "{{password}}",
  "provider": "{{provider}}",
  "providerAccountId": "{{providerAccountId}}"
}

> {%
  client.global.set("accountId", response.body.data._id)
%}

### Get all accounts
GET {{api_endpoint}}/accounts

### Get account by id
GET {{api_endpoint}}/accounts/{{accountId}}

### Update account by id
PUT {{api_endpoint}}/accounts/{{accountId}}

{
  "userId": "{{userId}}",
  "name": "{{name}}",
  "image": "{{image}}",
  "password": "{{password}}",
  "provider": "{{provider}}",
  "providerAccountId": "{{providerAccountId}}"
}

### Delete account by id
DELETE {{api_endpoint}}/accounts/{{accountId}}

### Get account by provider id
POST {{api_endpoint}}/accounts/{{providerAccountId}}

{
  "providerAccountId": "{{providerAccountId}}"
}
