export const ROUTES = {
  HOME: "/",
  COMMUNITY: "/community",
  COLLECTIONS: "/collections",
  JOBS: "/jobs",
  TAGS: "/tags",
  TAG_BY_ID: "/tags/[tagId]",
  PROFILE_BY_ID: "/profile/[profileId]",
  PROFILE_UPDATE: "/profile/[profileId]/update",
  ASK_QUESTION: "/ask-question",
  QUESTIONS: "/questions",
  QUESTION_BY_ID: "/questions/[questionId]",
  QUESTION_UPDATE: "/questions/[questionId]/update",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
} as const;
