### Get all users
GET {{api_endpoint}}/users

### Create a user
POST {{api_endpoint}}/users

{
  "name": "Mykola Kravchenko",
  "username": "mykola.kravchenko",
  "email": "mykola.kravchenko@example.com"
}
